### ISSUE TITLE
 trainSic.lua:167: attempt to call global 'pearson' (a nil value)

### ISSUE THREAD

**Issue by SeekPoint** [castorini/VDPWI-NN-Torch#5]
--------------- EPOCH 1--- -------------	
Train Loss: 639.4666859851	
Finished epoch in 1313.973097086	
/home/mldl/torch/install/bin/luajit: trainSic.lua:167: attempt to call global 'pearson' (a nil value)
stack traceback:
	trainSic.lua:167: in main chunk
	[C]: in function 'dofile'
	...mldl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
mldl@mldlUB1604:~/ub16_prj/VDPWI-NN-Torch$

**Comment by hohoCode** [comment]
Thanks. 'pearson' should be a function. We have provided this in the codes.

**Comment by SeekPoint** [comment]
your will? or have it done?

**Comment by hohoCode** [comment]
You can use the following:

function pearson(x, y)
  x = x - x:mean()
  y = y - y:mean()
  return x:dot(y) / (x:norm() * y:norm())
end

**Comment by hohoCode** [comment]
Thanks for your comments. This function used to be there. Now we have added it back, and things should all be working again. If not please let us know. Thanks.
